# Header
menu:
  所有文章: /archives
  标签云: /tags/
  留言板: /about/
  建站日志: /2015/08/20/blog-building

# SubNav
subnav:
  # RSS plugin: https://github.com/hexojs/hexo-generator-feed
  # Encrypt email 加密邮件地址 http://tool.chacuo.net/commonhideinfo
  Email: "mailto:&#0000109;&#0000111;&#x0000031;&#0048;&#x0000030;&#0048;&#000053;&#000064;&#00000111;&#0117;&#00116;&#x000006c;&#0111;&#111;&#00107;&#x002e;&#x00063;&#00000111;&#00109;"
  新浪微博: //weibo.com/yemzh
  GitHub: //github.com/MOxFIVE
  V2EX: //www.v2ex.com/member/MOxFIVE
  RSS: "/atom.xml"
  #知乎: "zhihu"
  #豆瓣: "douban"
  #Facebook: "#"
  #Google: "#"
  Twitter: "//twitter.com/MOxFE"
  #LinkedIn: "#"
  #QQ: "#"
  #微信: "Wechat"
  #PayPal: "#"
  #StackOverflow: "#"
  #Instagram: "#"
  #Flickr: "#"
  TiddlyWiki: "/wiki/"

# Customize feed link 自定义订阅地址
rss: /atom.xml

# "5": show images form bg-1.jpg to bg-5.jpg in `/yelee/source/background/`
# "5": 显示`/yelee/source/background/`文件夹中 bg-1.jpg 到 bg-5.jpg 这5张图片
# "0": white-gray background | 淳朴灰白背景
background_image: 5

# Content
excerpt_link: more
fancybox: true
mathjax: 0

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
#google_analytics: ''
favicon: /resources/favicon.ico

#你的头像url
avatar: /resources/Mihawk.png

#是否开启分享
share: true

#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#注册多说后，地址前面的就是你的 duoshuo-key http://duoshuo-key.duoshuo.com
duoshuo: moxfive

#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  Hexo: //hexo.io
  GitHub: //pages.github.com/
  Netcan: //netcanblog.sinaapp.com/
  Jackie Wu: //jackieblog.github.io/
  Andy Zheng: //codinglife.in/
  skyxuan: //syncshinee.github.io/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 专注于前端

#是否显示边栏中的搜索框 
#Search Box in left column
search_box: true

#Keep TOC title on the same line.
#目录中标题不换行
#toc_nowrap: true


# >>> Style Customisation 样式自定义 <<<

highlight_style:
  on: true
  inline_code: 1  # Value: 0 - 9 可用
  code_block: 1  # Value: 0 - 4 
  # Set inline_code to style highlight text
  # Chose a highlight theme for code block
  # 通过 inline_code 切换内置文本高亮样式
  # 通过 code_block 切换内置代码高亮配色主题

# >>> <<<

blockquote_style:
  #on: true
  blockquote: 1
