# Header
menu:
  #主页: /
  所有文章: /archives
  留言板: /about
  #标签: /tags
  建站日志: /2015/08/20/blog-building/

# SubNav
subnav:
  邮件: "mailto:&#0000109;&#0000111;&#x0000031;&#0048;&#x0000030;&#0048;&#000053;&#000064;&#00000111;&#0117;&#00116;&#x000006c;&#0111;&#111;&#00107;&#x002e;&#x00063;&#00000111;&#00109;"
  新浪微博: http://weibo.com/yemzh
  GitHub: https://github.com/MOxFIVE
  V2EX: https://www.v2ex.com/member/MOxFIVE
  #Facebook: "#"
  #Google: "#"
  #Twitter: "#"
  #Linkedin: "#"
  RSS订阅: /atom.xml
  #知乎: "#"
  #豆瓣: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
# google_analytics: ''
favicon: /resources/favicon.ico

#你的头像url
avatar: /resources/Mihawk_312.png
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
duoshuo: moxfive
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  Hexo: https://hexo.io
  GitHub Pages: https://pages.github.com/



#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 专注于前端